### ISSUE TITLE
Compiling v7files...

### ISSUE THREAD

**Issue by abhas** [thiloplanz/v7files#9]
I guess I need to compile the code before I run it or use it. Are there any instructions on how to compile and run v7files?

**Comment by thiloplanz** [comment]
There has not been a release yet, so yes, you cannot download binaries and have to build v7files yourself for now.

This is done with Maven, I have added instructions on the wiki: https://github.com/thiloplanz/v7files/wiki/Installation

The plan is to have a 0.1 release by June, and then there will be an executable jar file for download.

As for running, please try the instructions in the README file: make a configuration file and run the "serve" command.

**Comment by abhas** [comment]
Thanks a lot... I'm trying this out right now! :)
